import {
  MessageSquare, Users, LayoutDashboard, Kanban, Bot, Database,
  Palette, Settings, Bell, Plus, Send, Loader2, X, Check, ChevronDown,
  ChevronRight, Upload, Trash2, Edit, Copy, ExternalLink, Calendar,
  DollarSign, FileText, Building2, User, Mail, Phone, Search,
  Filter, Download, MoreVertical, AlertCircle, Info, CheckCircle,
  XCircle, Clock, TrendingUp, TrendingDown, BarChart3, PieChart,
  Image, Video, Hash, Heart, MessageCircle, Share2, Eye, Bookmark,
  Briefcase, CreditCard, Receipt, FileSignature, FolderOpen, 
  ArrowUpRight, ArrowDownRight, RefreshCw, LogOut, Moon, Sun,
  Menu, Home, Zap, Target, Award, Star, Package, Globe, Lock, Unlock
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Chat: MessageSquare,
  Kanban,
  Agents: Bot,
  Knowledge: Database,
  Studio: Palette,
  Settings,
  Users,
  Home,
  Menu,
  Plus,
  Send,
  Loader: Loader2,
  Close: X,
  Check,
  ChevronDown,
  ChevronRight,
  Upload,
  Delete: Trash2,
  Edit,
  Copy,
  ExternalLink,
  Download,
  More: MoreVertical,
  Search,
  Filter,
  Refresh: RefreshCw,
  LogOut,
  Bell,
  Alert: AlertCircle,
  Info,
  Success: CheckCircle,
  Error: XCircle,
  Clock,
  Money: DollarSign,
  CreditCard,
  Receipt,
  TrendingUp,
  TrendingDown,
  Client: Building2,
  User,
  Mail,
  Phone,
  Calendar,
  Contract: FileSignature,
  Document: FileText,
  Folder: FolderOpen,
  Briefcase,
  BarChart: BarChart3,
  PieChart,
  Image,
  Video,
  Hash,
  Heart,
  Comment: MessageCircle,
  Share: Share2,
  Eye,
  Bookmark,
  ArrowUp: ArrowUpRight,
  ArrowDown: ArrowDownRight,
  Moon,
  Sun,
  Zap,
  Target,
  Award,
  Star,
  Package,
  Globe,
  Lock,
  Unlock
};

export default Icons;
